# Find SDL
# Defines:
# ${SDL2_INCLUDE_DIRS} 
# ${SDL2_LIBRARIES}

if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(VC_LIB_PATH_SUFFIX lib/x64)
else()
  set(VC_LIB_PATH_SUFFIX lib/x86)
endif()

FIND_PATH(SDL2_INCLUDE_DIR
  NAMES
  SDL.h
  HINTS
   ${CMAKE_SOURCE_DIR}/ext/SDL2-2.0.12/
  PATH_SUFFIXES
    include
)
FIND_LIBRARY(SDL2_LIBRARY
  NAMES
  SDL2
  HINTS
  ${CMAKE_SOURCE_DIR}/ext/SDL2-2.0.12/${VC_LIB_PATH_SUFFIX}
  PATH_SUFFIXES
    lib64 lib
  )

# handle the QUIETLY and REQUIRED arguments and set SDL2_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 DEFAULT_MSG SDL2_LIBRARY SDL2_INCLUDE_DIR)

IF(SDL2_FOUND)
message("Found SDL2: include:" ${SDL2_INCLUDE_DIR} " lib:" ${SDL2_LIBRARY})
  SET(SDL2_LIBRARIES ${SDL2_LIBRARY})
  SET(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})
ENDIF(SDL2_FOUND)

MARK_AS_ADVANCED(
  SDL2_INCLUDE_DIR
  SDL2_LIBRARY
)
